

export const authActionTypes = {

    SIGN_IN_SUCCESS: "SIGN_IN_SUCCESS",
    SIGN_IN_FAILURE: "SIGN_IN_FAILURE",
    SIGN_IN_START: 'SIGN_IN_START',

    SIGN_OUT_START: 'SIGN_OUT_START',
    SIGN_OUT_SUCCESS: "SIGN_OUT_SUCCESS",
    SIGN_OUT_FAILURE: "SIGN_OUT_FAILURE",

    LOADING_IN_START: 'LOADING_IN_START',
    LOADING_IN_CANCEL: 'LOADING_IN_CANCEL',

    THEME_TOGGLE_START: 'THEME_TOGGLE_START',
    THEME_TOGGLE_END: 'THEME_TOGGLE_END',

    RESUME_LINK_SSE_START: 'RESUME_LINK_SSE_START',
    RESUME_LINK_SSE_SUCCESS: 'RESUME_LINK_SSE_SUCCESS',

    NOTIFICATION_IN_START: 'NOTIFICATION_IN_START',
    NOTIFICATION_IN_SUCCESS: 'NOTIFICATION_IN_SUCCESS',

    TASK_RESUME_OPEN: 'TASK_RESUME_OPEN',
    TASK_RESUME_CANCEL: 'TASK_RESUME_CANCEL',

    EXPORT_EXCEL: 'EXPORT_EXCEL',
}
